executor: "KubernetesExecutor"


images:
  airflow:
    repository: my-airflow-image
    tag: "0.1"
    digest: ~
    pullPolicy: IfNotPresent

    # values.yaml
postgresql:
  enabled: true
  image:
    tag: "13.2.0"
    repository: bitnamilegacy/postgresql

dags:
  gitSync:
    enabled: true

    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/amirfirouzi87/Airflow-on-K8s.git
    branch: main
    rev: HEAD
    # The git revision (branch, tag, or hash) to check out, v4 only
    ref: main
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags"
    credentialsSecret: git-credentials


logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs-pvc

