apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: YW1pcmZpcm91emk4Nw==
  GITSYNC_PASSWORD: Z2hwX293V1RWbjMwRzNvaGdTSDBVRWo3YUh0SlBJWnROMzBMb2RLbQ==
  GIT_SYNC_USERNAME: YW1pcmZpcm91emk4Nw==
  GIT_SYNC_PASSWORD: Z2hwX293V1RWbjMwRzNvaGdTSDBVRWo3YUh0SlBJWnROMzBMb2RLbQ==